### ISSUE TITLE
微信端单页面应用（SPA）微信支付路径问题

### ISSUE THREAD

**Issue by lmasdata** [Chooin/wechat-spa#1]
请问安卓中把‘#’ 替换 成‘?#’ 后，会导致页面重新刷新，有好的方法解决这种用户体验问题么

**Comment by chooin** [comment]
刚更新微信支付文档。
```
if (window.location.href.indexOf('?#') < 0) {
  window.history.pushState({}, '', '?#/cart/payment')
}
.. // 业务代码
```

**Comment by lmasdata** [comment]
谢谢，解决了大问题，可是刚才一试安卓上的微信支付又不行了，闪一下支付窗口就没了，请问这是路径的原因造成的么

**Comment by chooin** [comment]
配置wx.config非支付页面使用window.location.href.split('#')[0]，支付页面使用window.location.href。您是这样操作的嘛。方便提供下Android版本号？

**Comment by chooin** [comment]
配置wx.config可以参考下“微信分享”部分

**Comment by lmasdata** [comment]
你好，请问这里的url使用时用在微信config生成签名的地方么。有没有QQ或者微信方便交流下？

**Comment by chooin** [comment]
对的，将url提交到服务端，让服务端生成wx.config的签名信息。页面需要调用js-sdk都得重新配置wx.config，支付页面和非支付页面提交的url是不一样的。

**Comment by lmasdata** [comment]
现在没有使用wxconfig，而是用的老的方式
![image](https://cloud.githubusercontent.com/assets/8501594/23646886/efef39c6-034d-11e7-81e4-3fd138009410.png)
而且后台授权登录后返回到前台的地址中拼接了好多参数，
所以我感觉是支付路径的问题。

**Comment by lmasdata** [comment]
现在换成wx.config,在安卓中支付的时候提示choosewxpay fail
安卓版本7.0

**Comment by chooin** [comment]
涉及调用jsapi的页面都得重新配置wx.config

**Comment by lmasdata** [comment]
只有这一个页面用wx.config 还用重新配置吗

**Comment by chooin** [comment]
当然

**Comment by lmasdata** [comment]
谢谢大神，莫名其妙就解决了，不过安卓支付偶尔还是唤起不了支付框

**Comment by Chooin** [comment]
不客气，有啥问题随时可以交流😁

**Comment by chooin** [comment]
方便提供Android版本嘛

**Comment by chooin** [comment]
我测试过Android 4.x和Android 6.x都没什么问题

**Comment by lmasdata** [comment]
就是在6.x出现的这种问题。时好时坏的

**Comment by chooin** [comment]
加下我的QQ465353876
