### ISSUE TITLE
求助，不wx.config的情况下单页面如何做分享呢？

### ISSUE THREAD

**Issue by lilywang711** [Chooin/wechat-spa#14]
如题，不config 的情况下，分享每个页面出去时，对应的地址都能够一一对应，
www.a.com?#/user 分享出去=> www.a.com?#/user
目前似乎是只能识别到首次进入的那个网址，不知道有木有什么偏方可以做到这一点，求助

**Comment by chooin** [comment]
不配置 config 无法自定义分享，只会分享当前页面

**Comment by lilywang711** [comment]
@Chooin 不需要自定义分享，只需要在分享出去的时候，分享的是当前页面的网址就行了。
但是目前分享出去只会分享 '首次进入时候的网址'，就即使已经跳转到/b了，分享出去别人打开还是在/index

**Comment by chooin** [comment]
符合下面格式的 URL 应该是没问题的

http://www.baidu.com/#/product?share_at={随机数}

**Comment by chooin** [comment]
每次跳转路由的时候都产生一个随机参数，用标准一点的 hash 模式的 URL，如：www.a.com/#/user，而不是 www.a.com?#/user
