### ISSUE TITLE
后台是用springmvc，但是每次页面刷新就会报404这个怎么解决哈

### ISSUE THREAD

**Issue by zhangwei900808** [Chooin/wechat-spa#2]
你好，官网上面是配置apace 和nginx但是我是使用tomcat，请问下，我该怎么解决这个问题

**Comment by chooin** [comment]
和http服务器没什么关系吧。您也是用单页面技术去做微信的应用？

**Comment by zhangwei900808** [comment]
是阿，在调试的时候报签名错误，然后就想知道你们是怎么控制服务器端的，因为一刷新就报404

**Comment by chooin** [comment]
路由的hash务必是“#”

**Comment by zhangwei900808** [comment]
我是使用hash模式阿，没有使用history模式，但是还是报签名错，你有代码可以借我参考下吗，我看到底是哪步出现错误

**Comment by chooin** [comment]
加下我的QQ465353876

**Comment by zhangwei900808** [comment]
已经加了，求同意
