### ISSUE TITLE
微信支付路由设置

### ISSUE THREAD

**Issue by ziyoung** [Chooin/wechat-spa#3]
[微信支付](https://github.com/Chooin/wechat-spa#微信支付)这一段中提供的解决方式:
>  我们进入 SPA 应用的第一个页面都是 http://example.com/wx/ 然后通过 SPA 应用路由钩子重定向到自己想要访问的页面。

假设我现在http://example.com/wx/#/home/index ，然后我再刷新该页面，假设我现在是已经授权过了，那将不会跳转到授权登录页，首次进入的页面就变成了http://example.com/wx/#/home/index ，该方案也就失效了。

**Comment by homerious** [comment]
授权过的页面其实不用重复授权的。

**Comment by chooin** [comment]
这样的情况是会出现的，不过我们可以在页面刷新之前将当前的路由存储到本地，刷新完成后先跳转到 http://example.com/wx/ ，再通过路由勾子完成重定向
