### ISSUE TITLE
现在好像微信里的#路由不会更新了

### ISSUE THREAD

**Issue by limichange** [Chooin/wechat-spa#5]
如果你进入的是/#/，那么你不管怎么跳转，最后复制url的时候都是/#/

**Comment by chooin** [comment]
我在 iOS 11.2.2 微信 6.6.1 和 Android 平台测试了下，都能完整的复制出 URL，方便提供下你使用的系统和微信版本嘛

**Comment by limichange** [comment]
版本跟你一样。
如果你进入是`/#/`，然后跳转到了`/#/userCenter`，复制出来的url是什么？我一直都是`/#/`。
哪怕我在`/#/userCenter`里刷新了，复制的URL还是`/#/`。
诡异至极。

**Comment by chooin** [comment]
方便给个项目的地址嘛，或者加我 QQ 发送给我，QQ：465353876

**Comment by limichange** [comment]
用ssr的方式解决了
