### ISSUE TITLE
微信授权 直接重定向回 spa 页面   url  问题

### ISSUE THREAD

**Issue by qinouz** [Chooin/wechat-spa#7]
https://qa2-a.hfax.com/mobile/?code=011f9Dlo11ipDp0OInio1loOlo1f9Dlv&state=#/login

这是我重定向回来后的 url    哈希的位置很怪异，，，，

**Comment by chooin** [comment]
参考微信授权和微信分享，url 地址里面不要携带 “#”

**Comment by chooin** [comment]
完成微信授权回跳地址不要携带 “#”

**Comment by qinouz** [comment]
难道只能重定向回一个中间页么。。。。很蛋疼

**Comment by chooin** [comment]
肯定不是的！只要你控制好 # 后面的地址就可以了
