### ISSUE TITLE
"路由不要用history模式“应该改为不要用hash模式吧

### ISSUE THREAD

**Issue by shouhutianshi** [Chooin/wechat-spa#8]

**Comment by chooin** [comment]
为什么呢，你在开发中使用 hash 模式有碰到什么问题吗？

**Comment by shouhutianshi** [comment]
带‘#’是hash模式，不带是history模式，你不是指的不带‘#’吗

**Comment by chooin** [comment]
授权页面（auth.html）我是单独拎出来的

**Comment by jeffkit** [comment]
同问，用History模式会遇到什么问题？

**Comment by chooin** [comment]
@jeffkit 
1. 无法拷贝当前页面 URL
2. 微信支付安全目录问题（好久没写了，好像有这个问题）
