### ISSUE TITLE
请问怎么在#前加?呢?

### ISSUE THREAD

**Issue by we125182** [Chooin/wechat-spa#9]
使用的angular4, 路由hash模式. IOS微信支付遇到当前url未注册问题. 求助!

**Comment by chooin** [comment]
可以尝试我提供的授权方式或者弄一个空白的页面去支付

**Comment by we125182** [comment]
谢谢你的建议. 之前有考虑过使用你说的这种方式, 但这样的话, 对外的链接就会变为类似http://example.com?state=order/list的样子, 对外的分享也要做相应的处理. 现在已经可以了, 将路径中的"#"换成"?#".
